### PR TITLE
Adding support for auto-building docs on release + travis

### PR DESCRIPTION
**Pull request by gauntface**
@Garbee would appreciate your thoughts on this

cc @jeffposnick as an FYI

### CODE REVIEW

**Comment by Garbee** [comment]
just ran and checked out the output. LGTM for an initial start.

Minor nitpick on organization... usage/API should be under a "docs" heading while the recipes would fit best under a "Demos" heading leaving room for more later.

**Comment by gauntface** [comment]
This seems like a major downside of jsdoc (unless you know of a trick to
achieve this, but from looking the docs for jsdoc, everything has to be a
tutorial, within that we can maybe have docs and demos.

**Comment by Garbee** [comment]
May want to peek at [esdoc](https://esdoc.org/tutorial.html#create-config-file). It supports multiple "manual" pages that would fit the needs here.

However, that can be updated later. For now this works so I'm good with it.

**Comment by gauntface** [comment]
Cheers @Garbee

**Comment by addyosmani** [comment]
This LGTM. I'm down with us switching to ESDoc where needed as we evaluated it internally for DevRel projects and liked it too.

**Pull request merged**
