### PR TITLE
Companion: Avoid old IE errors with document.currentScript

### PR DESCRIPTION
**Pull request by gierschv**
This PR fixes the errors `TypeError: Unable to get property 'dataset' of undefined or null reference` on IE <= 11.

Thanks!
Vincent

### CODE REVIEW

**Comment by gierschv** [comment]
@googlebot I signed it!

**Comment by wibblymat** [comment]
Thanks!

**Comment by wibblymat** [comment]
Sorry @gierschv, I hadn't properly checked before. I can't match up your github name or the email address you used to commit the changes to a signed CLA. Did you maybe use a different email address?

**Comment by gierschv** [comment]
@wibblymat, vincent@tutteo.com, I signed the company CLA yesterday.

**Comment by wibblymat** [comment]
Ah, OK, corporate CLAs can take a few days to process.

I'm happy with the PR, so I'll check back that the lawyers are happy in a few days and merge.

**Comment by gierschv** [comment]
@wibblymat It should be ok now, I got the CLA on Docusign marked as completed.

**Comment by wibblymat** [comment]
@gierschv excellent, thanks for the PR!

**Pull request merged**
