### PR TITLE
update readme docs links

### LINKED ISSUE #121: some incorrect doc URLs in README
I think just these 3 need to be changed to:

```
[expressive approach](doc-pages/api.md#toolboxrouterheadurlpattern-handler-options) 
[usage](doc-pages/usage.md) 
[api](doc-pages/api.md)
```

### PR DESCRIPTION
**Pull request by psimyn**
fixes #121

### CODE REVIEW

**Comment by gauntface** [comment]
Could you possibly change the URLs to use the new docs: http://googlechrome.github.io/sw-toolbox/docs/master/

**Comment by psimyn** [comment]
Can do, except for the "expressive approach" link (there's also a few broken anchors in the usage/api doc pages).

Do you prefer squashed commits for PRs or I can just keep stacking them on?

**Comment by gauntface** [comment]
Squashed please :)

**Comment by psimyn** [comment]
updated and force pushed - https://googlechrome.github.io/sw-toolbox/docs/master/tutorial-api#toolboxrouterheadurlpattern-handler-options anchor is still broken - can try updating docs titles to be linkable if wanted

**Pull request merged**
