### PR TITLE
Brings automated mocha tests in alignment with qunit tests.

### PR DESCRIPTION
**Pull request by gauntface**
@wibblymat thoughts on this?

This adds some tests for options and removes the older qunit tests.

I noticed a few issues with the travis build when mocha fails so I've fixed that and I also spotted an issue with the sw-toolbox map not being generated in the right place so thats fixed now.

### CODE REVIEW

**Comment by addyosmani** [comment]
@gauntface This was filed a few weeks back. Are you still interested in this being brought in in it's current form (once reviewed)?

**Comment by gauntface** [comment]
I'll take a look at fixing up this PR and all tests in Firefox on Monday

**Comment by gauntface** [comment]
@addyosmani @wibblymat Thoughts on this PR?

**Comment by addyosmani** [comment]
@googlebot I'm a Googler. This is fine.

**Pull request merged**
