### PR TITLE
Removed obsolete dependencies

### PR DESCRIPTION
**Pull request by tHBp**
The service worker cache polyfill used is now declared obsolete according to repository maintainer(s) as support for `cache.addAll` is now available in Chrome Stable as well as Opera Stable.
See [this](https://github.com/dominiccooney/cache-polyfill/issues/17#issuecomment-158628413).

### CODE REVIEW

**Comment by tHBp** [comment]
I've signed it.

**Comment by tHBp** [comment]
Any update on this?

**Comment by Ganyanut** [comment]
I signed it!

**Comment by tHBp** [comment]
Any updates?
Pardon me if I'm being hasty, as I'm not familiar with the approval/access flow for merging pull requests to repositories maintained by Google.

**Comment by jeffposnick** [comment]
Sorry about that—thanks for the contribution. Agreed that the polyfill shouldn't be necessary anymore.

**Pull request merged**
